import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Framer-Motion-POC",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}  bg-zinc-900  scrollbar scrollbar-w-1 rounded scrollbar-thumb-rounded-lg scrollbar-track-rounded-lg scrollbar-thumb-zinc-700 scrollbar-track-zinc-300`}
      >
        {children}
      </body>
    </html>
  );
}
